on:
  workflow_dispatch:
jobs:
  push_to_codeberg:
    name: Push to Codeberg
    runs-on: ubuntu-latest
    steps:
      - name: Clone from GitHub
        run: git clone https://github.com/ehanahamed/purpleish.git
      - name: Push to Codeberg
        run: |
          cd purpleish
          git push https://ehanahamed:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/ehanahamed/purpleish.git --all
